image: dtzar/helm-kubectl:3.5.3

stages:
  - lint
  - upload

lint:
  stage: lint
  rules:
    - if: '$CI_COMMIT_TAG == "/^$/"'
  script:
    - helm lint .

upload:
  stage: upload
  rules:
    - if: '$CI_COMMIT_TAG =~ "/^$/"'
  before_script:
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm repo add --username ${DEPLOY_USERNAME} --password ${DEPLOY_PASSWORD} ${CI_PROJECT_NAME} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
    - helm cm-push . ${CI_PROJECT_NAME}
