image: alpine/helm:3.10.1

stages:
  - upload

upload:
  stage: upload
  before_script:
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm repo add --username ${DEPLOY_USERNAME} --password ${DEPLOY_PASSWORD} ${CI_PROJECT_NAME} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
    - helm package ./ -d ./dist
    - helm cm-push $(ls ./dist) ${CI_PROJECT_NAME}
