{{- define "yauhc.configmap.tpl" }}
{{- $global :=  (.global | default dict) -}}
{{- $generic := (.generic | default dict) -}}
{{- $app := . -}}
{{- $appConfigs := (include "yauhc.util.merger" (list $app.configs $generic.configs $global.configs)) -}}
{{- $appName := $app.name -}}
{{- $configmapExt := (include "yauhc.util.selecter" (list $app.configmapName $generic.configmapName $global.configmapName "settings")) -}}
{{- if and ($appName) ($appConfigs) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $appName }}-configmap-{{ $configmapExt }}
  labels:
    app: {{ $appName }}
data:
  {{ $appConfigs }}
{{- end }}
{{- end }}
{{- define "yauhc.configmap" -}}
{{- include "yauhc.util.merge" (append . "yauhc.configmap.tpl") -}}
{{- end -}}
