{{- define "yauhc.deployment.tpl" -}}
{{- $global :=  (.global | default dict) -}}
{{- $generic := (.generic | default dict) -}}
{{- $app := . -}}
{{- $appImage := (include "yauhc.util.selecter" (list $app.image $generic.image $global.image)) -}}
{{- $appName := $app.name -}}
{{- if and (include "yauhc.util.selecter" (list $app.enable $generic.enable $global.enable)) ($appImage) ($appName) }}
{{- $appLabels := dict "app" $appName -}}
{{- $configmapExt := (include "yauhc.util.selecter" (list $app.configmapSuffix $generic.configmapSuffix $global.configmapSuffix "settings")) -}}
{{- $configmapMountPath := (include "yauhc.util.selecter" (list $app.configPath $generic.configPath $global.configPath (printf "/etc/%s" $appName ))) -}}
{{- $kind := (include "yauhc.util.selecter" (list $app.kind $generic.kind $global.kind)) -}}
{{- $appConfigs := (include "yauhc.util.merger" (list $app.configs $generic.configs $global.configs)) -}}
{{- $appVolumes := fromYaml (include "yauhc.util.merger" (list $app.volumes $generic.volumes $global.volumes)) -}}
{{- $containerAnnotations := dict -}}
{{- with $appConfigs -}}
{{- $_ := set $containerAnnotations "checksum/config" (toJson $appConfigs | sha256sum) -}}
{{- end -}}
{{- if not $kind -}}
{{- if $appVolumes -}}
{{ $kind = "StatefulSet" }}
{{- else -}}
{{ $kind = "Deployment" }}
{{- end -}}
{{- end -}}
---
{{- if eq $kind "Deployment" }}
apiVersion: {{ include "capabilities.deployment.apiVersion" $ }}
{{- else if eq $kind "StatefulSet" }}
apiVersion: {{ include "capabilities.statefulset.apiVersion" $ }}
{{- else }}
apiVersion: {{ (include "yauhc.util.selecter" (list $app.apiVersion $generic.apiVersion $global.apiVersion )) }}
{{- end }}
kind: {{ $kind }}
metadata:
  name: {{ $appName }}
  labels:
    {{- with fromYaml (include "yauhc.util.merger" (list $appLabels $app.labels $generic.labels $global.labels)) }}
      {{- toYaml . | nindent 4 -}}
    {{- end}}
  {{- with fromYaml (include "yauhc.util.merger" (list $app.annotations $generic.annotations $global.annotations)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if eq $kind "StatefulSet"}}
  serviceName: {{ $appName }}
  {{- end }}
  {{- with (include "yauhc.util.selecter" (list $app.revisionHistoryLimit $generic.revisionHistoryLimit $global.revisionHistoryLimit)) }}
  revisionHistoryLimit: {{ . }}
  {{- end }}
  {{- with (include "yauhc.util.selecter" (list $app.replicaCount $generic.replicaCount $global.replicaCount)) }}
  replicas: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $appName }}
  {{- with fromYaml (include "yauhc.util.merger" (list $app.strategy $generic.strategy $global.strategy)) }}
  strategy:
      {{- . | nindent 4 }}
  {{- end }}
  {{- if and $appVolumes (eq $kind "StatefulSet") }}
  {{- range $name, $path := $appVolumes }}
  volumeClaimTemplates:
    - metadata:
        name: {{ $appName }}-{{ $name }}-data
      {{- with fromYaml (include "yauhc.util.merger" (list $app.volumeSpec $generic.volumeSpec (dict ))) }}
      spec:
          {{- toYaml . | nindent 8}}
      {{- end }}
  {{- end }}
  {{- end }}
  template:
    metadata:
      {{- with fromYaml (include "yauhc.util.merger" (list $containerAnnotations $app.annotations $generic.annotations $global.annotations)) }}
      annotations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with fromYaml (include "yauhc.util.merger" (list $appLabels $app.labels $generic.labels $global.labels)) }}
            {{- toYaml . | nindent 8 -}}
        {{- end}}
    spec:
      {{- if or $appConfigs (and $appVolumes (ne $kind "StatefulSet")) }}
      volumes:
        {{- if $appConfigs }}
        - name: {{ $appName }}-configmap
          configMap:
            name: {{ $appName }}-configmap-{{ $configmapExt }}
        {{- end }}
        {{- if ne $kind "StatefulSet" }}
        {{- range $name, $path := $appVolumes }}
        - name: {{ $appName }}-{{ $name }}-data
          {{- if eq $kind "Daemonset" }}
          hostPath:
            path: {{ $path }}
          {{- else if eq $kind "Deployment" }}
          persistentVolumeClaim:
            claimName: {{ $appName }}-{{ $name }}-volume
          {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- with (include "yauhc.util.selecter" (list $app.imagePullSecrets $generic.imagePullSecrets $global.imagePullSecrets)) }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ include "yauhc.util.selecter" (list $app.terminationGracePeriodSeconds $generic.terminationGracePeriodSeconds $global.terminationGracePeriodSeconds 30) }}
      containers:
        - name: {{ $appName }}
          imagePullPolicy: {{ include "yauhc.util.selecter" (list $app.imagePullPolicy $generic.imagePullPolicy $global.imagePullPolicy "IfNotPresent") }}
          image: {{ $appImage }}
          {{- with (include "yauhc.util.selecter" (list $app.command $generic.command $global.command)) }}
          command: {{ . }}
          {{- end }}
          {{- with fromYaml (include "yauhc.util.merger" (list $app.env $generic.env (dict ))) }}
          env:
            {{- range $name, $value := fromYaml . }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          {{- if or $appConfigs $appVolumes }}
          volumeMounts:
            {{- with $appConfigs }}
            - name: {{ $appName }}-configmap
              mountPath: {{ $configmapMountPath }}
              readOnly: true
            {{- end }}
            {{- range $name, $path := $appVolumes }}
            - name: {{ $appName }}-{{ $name }}-data
              mountPath: {{ $path }}
            {{- end }}
          {{- end }}
          {{- with fromYaml (include "yauhc.util.merger" (list $app.readinessProbe $generic.readinessProbe $global.readinessProbe)) }}
          readinessProbe: {{ toYaml . | nindent 12}}
          {{- end }}
          {{- with fromYaml (include "yauhc.util.merger" (list $app.livenessProbe $generic.livenessProbe $global.livenessProbe)) }}
          livenessProbe: {{ toYaml . | nindent 12}}
          {{- end }}
          {{- with fromYaml (include "yauhc.util.merger" (list $app.startupProbe $generic.startupProbe $global.startupProbe)) }}
          startupProbe: {{ toYaml . | nindent 12}}
          {{- end }}
          {{- with fromYaml (include "yauhc.util.merger" (list $app.resources $generic.resources $global.resources)) }}
          resources: {{ toYaml . | nindent 12}}
          {{- end }}
      {{- with fromYaml (include "yauhc.util.merger" (list $app.nodeSelector $generic.nodeSelector $global.nodeSelector)) }}
      nodeSelector: {{ toYaml . | nindent 8}}
      {{- end }}
      {{- with fromYaml (include "yauhc.util.merger" (list $app.affinity $generic.affinity $global.affinity)) }}
      affinity: {{ toYaml . | nindent 8}}
      {{- end }}
      {{- with fromYaml (include "yauhc.util.merger" (list $app.tolerations $generic.tolerations $global.tolerations)) }}
      tolerations: {{ toYaml . | nindent 8}}
      {{- end }}

{{- end }}
{{- end }}
{{- define "yauhc.deployment" -}}
{{- include "yauhc.util.merge" (append . "yauhc.deployment.tpl") -}}
{{- end -}}
