{{- $global := .Values.global -}}
{{- $generic := .Values.generic -}}
{{- $values := .Values -}}
{{- $capabilities := .Capabilities -}}
{{- $release := .Release -}}
{{- $chart := .Chart -}}
{{- $endpoints := (list) -}}
{{ range $i, $deployment := .Values.deployments }}
{{- $_ := set $deployment "generic" $generic -}}
{{- $_ = set $deployment "global" $global -}}
{{- $_ = set $deployment "Release" $release -}}
{{- $_ = set $deployment "Chart" $chart -}}
{{- $_ = set $deployment "Values" $values -}}
{{- $_ = set $deployment "Capabilities" $capabilities -}}
{{- if not $deployment.name -}}
{{- $_ = set $deployment "name" (printf "%s-%d" $release.Name $i) -}}
{{- end -}}

{{ include "yauhc.deployment.tpl" $deployment }}

{{- $appConfigs := (include "yauhc.util.merger" (list $deployment.configs $generic.configs $global.configs)) }}

{{- with $appConfigs }}
{{ include "yauhc.configmap.tpl" $deployment }}
{{- end }}

{{ include "yauhc.service.tpl" $deployment }}

{{- $appPort :=  (include "yauhc.util.selecter" (list $deployment.port $generic.port $global.port)) }}
{{- $ingressMap := dict "path" "/" "name" $deployment.name "port" $appPort }}

{{- if and $deployment.name $appPort $deployment.domain }}
{{- $_ = set $deployment "serviceMap" (list $ingressMap) }}
{{ include "yauhc.ingress.tpl" $deployment }}
{{- end }}

{{- if and ($deployment.name) ($appPort) ($deployment.endpointPath) }}
{{- $endpoints = concat $endpoints (list $ingressMap) }}
{{- end }}

{{ end }}

{{- $ingress := .Values.multi_endpoint }}
{{- $_ := set $ingress "name" (printf "endpoints-%s" .Release.Name) }}
{{- $_ = set $ingress "global" $global }}
{{- $_ = set $ingress "generic" $generic }}
{{- $_ = set $ingress "Release" $release -}}
{{- $_ = set $ingress "Chart" $chart -}}
{{- $_ = set $ingress "Values" $values -}}
{{- $_ = set $ingress "Capabilities" $capabilities -}}
{{- $_ = set $ingress "serviceMap" $endpoints }}
{{ include "yauhc.ingress.tpl" $ingress }}
